### ISSUE TITLE
Cannot generate .cs file 

### ISSUE THREAD

**Issue by jcohen120** [christianhelle/apiclientcodegen#388]
I click on 'New REST API Client'  > Generate with OpenAPI Generator - I then enter the Specification URL. 

Only the Swagger.json file is being generated and not the Swagger.cs file. I've looked through the documentation and cannot figure out why the Swagger.cs file is not being generated. 

I can provide additional information if needed. 

Thank you!

**Comment by jcohen120** [comment]
I right-clicked on the Swagger.json file and clicked 'Run Custom Tool' (which is OpenApiCodeGenerator) and it still does not produce the Swagger.cs file.

**Comment by jcohen120** [comment]
Additional code error info I just found

7/5/2022 2:30:39 PM: openapi-generator-cli.jar not found. Attempting to download openapi-generator-cli.jar
7/5/2022 2:31:00 PM: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 146.75.36.209:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Core.Installer.WebDownloader.DownloadFile(String address, String filename)
   at ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Core.Installer.FileDownloader.DownloadFile(String outputFilename, String expectedChecksumMd5, String url, Boolean forceDownload)
   at ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Core.Installer.DependencyInstaller.InstallOpenApiGenerator()
   at ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Core.Generators.OpenApi.OpenApiCSharpCodeGenerator.GenerateCode(IProgressReporter pGenerateProgress)
   at ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.CustomTool.SingleFileCodeGenerator.Generate(String wszInputFilePath, String bstrInputFileContents, String wszDefaultNamespace, IntPtr[] rgbOutputFileContents, UInt32& pcbOutput, IVsGeneratorProgress pGenerateProgress)
7/5/2022 2:31:00 PM: Unable to generate code
7/5/2022 2:31:00 PM: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 146.75.36.209:443
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Core.Installer.WebDownloader.DownloadFile(String address, String filename)
   at ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Core.Installer.FileDownloader.DownloadFile(String outputFilename, String expectedChecksumMd5, String url, Boolean forceDownload)
   at ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Core.Installer.DependencyInstaller.InstallOpenApiGenerator()
   at ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Core.Generators.OpenApi.OpenApiCSharpCodeGenerator.GenerateCode(IProgressReporter pGenerateProgress)
   at ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.CustomTool.SingleFileCodeGenerator.Generate(String wszInputFilePath, String bstrInputFileContents, String wszDefaultNamespace, IntPtr[] rgbOutputFileContents, UInt32& pcbOutput, IVsGeneratorProgress pGenerateProgress)

**Comment by jcohen120** [comment]
Apologies. The issue had to do with running the custom tool when connected to my company's VPN.
