### ISSUE TITLE
Generate with Kiota doesn't work on Visual Studio for Mac when using ZSH as default shell

### ISSUE THREAD

**Issue by christianhelle** [christianhelle/apiclientcodegen#497]
**Describe the bug**
**Generate with Kiota** context menu doesn't work on Visual Studio for Mac 2022 when using ZSH as the default shell

**To Reproduce**
1. Right click a project file, select Add -> New REST API Client -> Generate with Kiota 
2. Insert URL to Swagger Petstore v3 OpenAPI spec
3. Wait for NuGet packages to be installed after a couple of project reloads

**Expected behavior**
A code behind file is generated for the newly added OpenAPI spec file

**Screenshots**

**Visual Studio Extension (please complete the following information):**
 - Visual Studio Version: Visual Studio for Mac 2022
 - Extension Version: v1.7.2

**Additional context**

The tool outputs the following

```bash
Executing:
dotnet tool install --global Microsoft.OpenApi.Kiota --version 1.0.1
Tools directory '/Users/christian/.dotnet/tools' is not currently on the PATH environment variable.
If you are using zsh, you can add it to your profile by running the following command:

cat << \EOF >> ~/.zprofile
# Add .NET Core SDK tools
export PATH="$PATH:/Users/christian/.dotnet/tools"
EOF

And run `zsh -l` to make it available for current session.

You can only add it to the current session by running the following command:

export PATH="$PATH:/Users/christian/.dotnet/tools"

You can invoke the tool using the following command: kiota
Tool 'microsoft.openapi.kiota' (version '1.0.1') was successfully installed.

PROGRESS: 30%

PROGRESS: 40%
Executing:
kiota  generate -l CSharp -d ./Swagger.json -o /var/folders/6f/sxylb9b11ln1f9cbcyc6r9jh0000gn/T/fde34d26-ea98-449a-893e-fc93c31d47fb -n GeneratedCode
Error: An error occurred trying to start process 'kiota' with working directory '/Users/christian/projects/testapp'. No such file or directory
```

**Comment by aloksharma1** [comment]
Its not working on windows too, with following warning and erorr in package versions

```
29-06-2023 10:21:19 AM: Successfully installed Microsoft.Kiota.Serialization.Text version 1.0.1
29-06-2023 10:21:19 AM: Executing:
29-06-2023 10:21:19 AM: C:\Program Files\dotnet\dotnet.exe tool install --global Microsoft.OpenApi.Kiota --version 1.3.0
29-06-2023 10:21:23 AM: C:\Users\Alok\AppData\Local\Temp\f6488ebf-8d35-4a2a-97b6-4091f6f68a6f\restore.csproj : error NU1202: Package Microsoft.OpenApi.Kiota 1.3.0 is not compatible with net6.0 (.NETCoreApp,Version=v6.0) / any. Package Microsoft.OpenApi.Kiota 1.3.0 supports: net7.0 (.NETCoreApp,Version=v7.0) / any
29-06-2023 10:21:23 AM: The tool package could not be restored.
29-06-2023 10:21:23 AM: Tool 'microsoft.openapi.kiota' failed to install. This failure may have been caused by:
29-06-2023 10:21:23 AM: 
29-06-2023 10:21:23 AM: * You are attempting to install a preview release and did not use the --version option to specify the version.
29-06-2023 10:21:23 AM: * A package by this name was found, but it was not a .NET tool.
29-06-2023 10:21:23 AM: * The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
29-06-2023 10:21:23 AM: 
29-06-2023 10:21:23 AM: * You mistyped the name of the tool.
29-06-2023 10:21:23 AM: 
29-06-2023 10:21:23 AM: For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
29-06-2023 10:21:23 AM: 
29-06-2023 10:21:24 AM: Executing:
29-06-2023 10:21:24 AM: kiota  generate -l CSharp -d ProjectPath\Swagger.yaml -o C:\Users\Alok\AppData\Local\Temp\066d4b20-4b3a-442d-b2ad-1ae244babdb2 -n ProjectName
29-06-2023 10:21:24 AM: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Rapicgen.Core.Generators.ProcessLauncher.StartInternal(String command, String arguments, Action`1 onOutputData, Action`1 onErrorData, String workingDirectory)
   at Rapicgen.Core.Generators.ProcessLauncher.Start(String command, String arguments, Action`1 onOutputData, Action`1 onErrorData, String workingDirectory)
   at Rapicgen.Core.Generators.ProcessLauncher.Start(String command, String arguments, String workingDirectory)
   at Rapicgen.Core.Generators.Kiota.KiotaCodeGenerator.GenerateCode(IProgressReporter pGenerateProgress)
   at Rapicgen.CustomTool.SingleFileCodeGenerator.Generate(String wszInputFilePath, String bstrInputFileContents, String wszDefaultNamespace, IntPtr[] rgbOutputFileContents, UInt32& pcbOutput, IVsGeneratorProgress pGenerateProgress)
29-06-2023 10:21:24 AM: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Rapicgen.Core.Generators.ProcessLauncher.StartInternal(String command, String arguments, Action`1 onOutputData, Action`1 onErrorData, String workingDirectory)
   at Rapicgen.Core.Generators.ProcessLauncher.Start(String command, String arguments, Action`1 onOutputData, Action`1 onErrorData, String workingDirectory)
   at Rapicgen.Core.Generators.ProcessLauncher.Start(String command, String arguments, String workingDirectory)
   at Rapicgen.Core.Generators.Kiota.KiotaCodeGenerator.GenerateCode(IProgressReporter pGenerateProgress)
   at Rapicgen.CustomTool.SingleFileCodeGenerator.Generate(String wszInputFilePath, String bstrInputFileContents, String wszDefaultNamespace, IntPtr[] rgbOutputFileContents, UInt32& pcbOutput, IVsGeneratorProgress pGenerateProgress)
29-06-2023 10:21:24 AM: Unable to generate code
29-06-2023 10:21:24 AM: 
```


```
29-06-2023 10:22:27 AM: Generating code using Kiota
29-06-2023 10:22:27 AM: Checking required dependencies
29-06-2023 10:22:27 AM: Azure.Identity is already installed
29-06-2023 10:22:27 AM: Installing Microsoft.Kiota.Abstractions version 1.1.2
29-06-2023 10:22:28 AM: NuGet.PackageManagement.PackageReferenceRollbackException: Package restore failed. Rolling back package changes for 'UnlimitedTravelSources.ExternalApi.HotelBeds'.
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteBuildIntegratedProjectActionsAsync>d__89.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__86.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<InstallPackageAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.<InstallInternalCoreAsync>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.<InstallInternalAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.<InstallInternalAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.VisualStudio.Implementation.Extensibility.VsPackageInstaller.InstallPackage(String source, Project project, String packageId, String version, Boolean ignoreDependencies)
   at Rapicgen.Extensions.ProjectExtensions.InstallPackageDependency(Project project, PackageDependency packageDependency, IReadOnlyCollection`1 installedPackages, IVsPackageInstaller packageInstaller)
29-06-2023 10:22:28 AM: Unable to install Microsoft.Kiota.Abstractions version 1.1.2
29-06-2023 10:22:28 AM: Microsoft.Kiota.Authentication.Azure is already installed
29-06-2023 10:22:28 AM: Microsoft.Kiota.Http.HttpClientLibrary is already installed
29-06-2023 10:22:28 AM: Microsoft.Kiota.Serialization.Form is already installed
29-06-2023 10:22:28 AM: Microsoft.Kiota.Serialization.Json is already installed
29-06-2023 10:22:28 AM: Microsoft.Kiota.Serialization.Text is already installed
```


there is a package mismatch in Kiota with abstraction version Microsoft.Kiota.Abstractions and other issues are as showing in logs.

**Comment by christianhelle** [comment]
Visual Studio for Mac is a dying product and this is no longer relevant
