### ISSUE TITLE
The "OpenApiReference" rule is missing the "Generator" property.

### ISSUE THREAD

**Issue by rkralston** [christianhelle/apiclientcodegen#63]
I am using VS 2019 the latest release.

I have added an openapi 3.0.1 json file to my project using Add Service Reference. I right click on the json file in Solution Explorer and select REST API Client Generator > Generate with OpenAPI. I get the error below:
10/25/2019 5:20:11 PM: Generating code using OpenApi
10/25/2019 5:20:11 PM: devenv.exe Error: 0 : 
10/25/2019 5:20:11 PM: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: The "OpenApiReference" rule is missing the "Generator" property.
   at Microsoft.Verify.Operation(Boolean condition, String unformattedMessage, Object arg1, Object arg2)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.DynamicTypeBrowseObject.<>c__DisplayClass12_0.<<VSLangProj-FileProperties-set_CustomTool>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.<>c__DisplayClass576_0.<<Mutate>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.ProjectSystem.ProjectMultiThreadedService.ExecuteSynchronously(Func`1 asyncAction)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.ProjectNode.Mutate(Func`1 asyncAction, Boolean includesFileSystemChange, String telemetryActivity)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.DynamicTypeBrowseObject.VSLangProj.FileProperties.set_CustomTool(String value)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.PropertyPages.DynamicTypeBrowseObject.VSLangProj80.FileProperties2.set_CustomTool(String value)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Microsoft.VisualStudio.ProjectSystem.VS.Implementation.Package.Automation.OAPropertyInfo.set_Value(Object value)
   at ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Commands.CustomTool.CustomToolSetter`1.<OnExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ChristianHelle.DeveloperTools.CodeGenerators.ApiClient.Extensions.AsyncPackageExtensions.<InvokeAsync>d__1.MoveNext()

**Comment by christianhelle** [comment]
First of all, thanks for taking your time to report this!

I don't know what the **Add Service Reference** does but I assume that there is some connected service tool that will download the OpenAPI / Swagger spec file, or perhaps use it to generate something else. 

Have you tried adding the OpenAPI / Swagger spec file using the **New REST API Client** Project context menu that I created? This approach will just download the spec file from the URL you specify

![](https://github.com/christianhelle/apiclientcodegen/raw/master/images/add-new-menu.png)
![](https://github.com/christianhelle/apiclientcodegen/raw/master/images/add-new-dialog.png)

Anyway, what my tool does is actually just piggy back on top the the OpenAPI Code Generator CLI tool which I download on-demand

I would love to help with troubleshooting this and I will also reach out to the OpenAPI Code Generator guys when I see that there is something they should do from their side. Do you mind sharing OpenAPI / Swagger spec file? You can send it to me by email (christian.helle [at] outlook.com) to keep it between us.

**Comment by rkralston** [comment]
I'll give that a try.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
