### ISSUE TITLE
Plugin is not working in VS 2017

### ISSUE THREAD

**Issue by chrbkr** [christianhelle/apiclientcodegen#97]
Executing any of the "Generate with..." options fails.

In the Error List, VS says:
_A custom tool 'OpenApiCodeGenerator' is associated with file 'ExampleREST.json', but the output of the custom tool was not found in the project. You may try re-running the custom tool by right-clicking on the file in the Solution Explorer and choosing Run Custom Tool._

In the activity log, I found:
_CreateInstance failed for package [VsPackage]Source: 'mscorlib' Description: Could not load file or assembly 'Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Das System kann die angegebene Datei nicht finden.
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. Das System kann die angegebene Datei nicht finden.
File name: 'Microsoft.VisualStudio.Shell.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)_

When checking the options, Visual Studio just shows "An error occurred loading this property page".

**Comment by christianhelle** [comment]
Working on this and I expect a fix in a few hours

**Comment by christianhelle** [comment]
This is now fixed in [v1.1.3189](https://github.com/christianhelle/apiclientcodegen/releases/tag/1.1.3189)

**Comment by chrbkr** [comment]
Thanks for the quick fix, works like a charm now!
